WillPaginate::ViewHelpers.pagination_options[:renderer] = 'MyLinkRenderer'
WillPaginate::ViewHelpers.pagination_options[:previous_label] = '&laquo; Previous'
WillPaginate::ViewHelpers.pagination_options[:next_label] = 'Next &raquo;'
WillPaginate::ViewHelpers.pagination_options[:first_label] = '&laquo; First'
WillPaginate::ViewHelpers.pagination_options[:last_label] = 'Last &raquo;'