require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # ContactGroup. As you add validations to ContactGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all contact_groups as @contact_groups" do
      contact_group = ContactGroup.create! valid_attributes
      get :index
      assigns(:contact_groups).should eq([contact_group])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_group as @contact_group" do
      contact_group = ContactGroup.create! valid_attributes
      get :show, :id => contact_group.id.to_s
      assigns(:contact_group).should eq(contact_group)
    end
  end

  describe "GET new" do
    it "assigns a new contact_group as @contact_group" do
      get :new
      assigns(:contact_group).should be_a_new(ContactGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_group as @contact_group" do
      contact_group = ContactGroup.create! valid_attributes
      get :edit, :id => contact_group.id.to_s
      assigns(:contact_group).should eq(contact_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContactGroup" do
        expect {
          post :create, :contact_group => valid_attributes
        }.to change(ContactGroup, :count).by(1)
      end

      it "assigns a newly created contact_group as @contact_group" do
        post :create, :contact_group => valid_attributes
        assigns(:contact_group).should be_a(ContactGroup)
        assigns(:contact_group).should be_persisted
      end

      it "redirects to the created contact_group" do
        post :create, :contact_group => valid_attributes
        response.should redirect_to(ContactGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_group as @contact_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroup.any_instance.stub(:save).and_return(false)
        post :create, :contact_group => {}
        assigns(:contact_group).should be_a_new(ContactGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroup.any_instance.stub(:save).and_return(false)
        post :create, :contact_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contact_group" do
        contact_group = ContactGroup.create! valid_attributes
        # Assuming there are no other contact_groups in the database, this
        # specifies that the ContactGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContactGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => contact_group.id, :contact_group => {'these' => 'params'}
      end

      it "assigns the requested contact_group as @contact_group" do
        contact_group = ContactGroup.create! valid_attributes
        put :update, :id => contact_group.id, :contact_group => valid_attributes
        assigns(:contact_group).should eq(contact_group)
      end

      it "redirects to the contact_group" do
        contact_group = ContactGroup.create! valid_attributes
        put :update, :id => contact_group.id, :contact_group => valid_attributes
        response.should redirect_to(contact_group)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_group as @contact_group" do
        contact_group = ContactGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => contact_group.id.to_s, :contact_group => {}
        assigns(:contact_group).should eq(contact_group)
      end

      it "re-renders the 'edit' template" do
        contact_group = ContactGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => contact_group.id.to_s, :contact_group => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_group" do
      contact_group = ContactGroup.create! valid_attributes
      expect {
        delete :destroy, :id => contact_group.id.to_s
      }.to change(ContactGroup, :count).by(-1)
    end

    it "redirects to the contact_groups list" do
      contact_group = ContactGroup.create! valid_attributes
      delete :destroy, :id => contact_group.id.to_s
      response.should redirect_to(contact_groups_url)
    end
  end

end
