require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactGroupsContactsController do

  # This should return the minimal set of attributes required to create a valid
  # ContactGroupsContact. As you add validations to ContactGroupsContact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all contact_groups_contacts as @contact_groups_contacts" do
      contact_groups_contact = ContactGroupsContact.create! valid_attributes
      get :index
      assigns(:contact_groups_contacts).should eq([contact_groups_contact])
    end
  end

  describe "GET show" do
    it "assigns the requested contact_groups_contact as @contact_groups_contact" do
      contact_groups_contact = ContactGroupsContact.create! valid_attributes
      get :show, :id => contact_groups_contact.id.to_s
      assigns(:contact_groups_contact).should eq(contact_groups_contact)
    end
  end

  describe "GET new" do
    it "assigns a new contact_groups_contact as @contact_groups_contact" do
      get :new
      assigns(:contact_groups_contact).should be_a_new(ContactGroupsContact)
    end
  end

  describe "GET edit" do
    it "assigns the requested contact_groups_contact as @contact_groups_contact" do
      contact_groups_contact = ContactGroupsContact.create! valid_attributes
      get :edit, :id => contact_groups_contact.id.to_s
      assigns(:contact_groups_contact).should eq(contact_groups_contact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContactGroupsContact" do
        expect {
          post :create, :contact_groups_contact => valid_attributes
        }.to change(ContactGroupsContact, :count).by(1)
      end

      it "assigns a newly created contact_groups_contact as @contact_groups_contact" do
        post :create, :contact_groups_contact => valid_attributes
        assigns(:contact_groups_contact).should be_a(ContactGroupsContact)
        assigns(:contact_groups_contact).should be_persisted
      end

      it "redirects to the created contact_groups_contact" do
        post :create, :contact_groups_contact => valid_attributes
        response.should redirect_to(ContactGroupsContact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contact_groups_contact as @contact_groups_contact" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroupsContact.any_instance.stub(:save).and_return(false)
        post :create, :contact_groups_contact => {}
        assigns(:contact_groups_contact).should be_a_new(ContactGroupsContact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroupsContact.any_instance.stub(:save).and_return(false)
        post :create, :contact_groups_contact => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contact_groups_contact" do
        contact_groups_contact = ContactGroupsContact.create! valid_attributes
        # Assuming there are no other contact_groups_contacts in the database, this
        # specifies that the ContactGroupsContact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContactGroupsContact.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => contact_groups_contact.id, :contact_groups_contact => {'these' => 'params'}
      end

      it "assigns the requested contact_groups_contact as @contact_groups_contact" do
        contact_groups_contact = ContactGroupsContact.create! valid_attributes
        put :update, :id => contact_groups_contact.id, :contact_groups_contact => valid_attributes
        assigns(:contact_groups_contact).should eq(contact_groups_contact)
      end

      it "redirects to the contact_groups_contact" do
        contact_groups_contact = ContactGroupsContact.create! valid_attributes
        put :update, :id => contact_groups_contact.id, :contact_groups_contact => valid_attributes
        response.should redirect_to(contact_groups_contact)
      end
    end

    describe "with invalid params" do
      it "assigns the contact_groups_contact as @contact_groups_contact" do
        contact_groups_contact = ContactGroupsContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroupsContact.any_instance.stub(:save).and_return(false)
        put :update, :id => contact_groups_contact.id.to_s, :contact_groups_contact => {}
        assigns(:contact_groups_contact).should eq(contact_groups_contact)
      end

      it "re-renders the 'edit' template" do
        contact_groups_contact = ContactGroupsContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContactGroupsContact.any_instance.stub(:save).and_return(false)
        put :update, :id => contact_groups_contact.id.to_s, :contact_groups_contact => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contact_groups_contact" do
      contact_groups_contact = ContactGroupsContact.create! valid_attributes
      expect {
        delete :destroy, :id => contact_groups_contact.id.to_s
      }.to change(ContactGroupsContact, :count).by(-1)
    end

    it "redirects to the contact_groups_contacts list" do
      contact_groups_contact = ContactGroupsContact.create! valid_attributes
      delete :destroy, :id => contact_groups_contact.id.to_s
      response.should redirect_to(contact_groups_contacts_url)
    end
  end

end
